name: "[TaaC] - Formulário para execução de testes no TaaC"
description: "Pedidos de execução de testes no TaaC"
title: "Formulário para execução de testes no TaaC "
labels: ["TaaC", "automatizacao", "testes"]
assignees:
  - ${{github.author}}
body:
  - type: markdown
    attributes:
      value: |
        Formulário para facilitar a execução dos testes no TaaC
        
  - type: input
    id: marks
    attributes:
      label: ">>Marks<<"
      description: Qual os marks que serão executados?
      placeholder: ex. lambda
    validations:
      required: true
      
  - type: textarea
    id: more-information
    attributes:
      label: ">>Informações adicionais<<"
      description: Informações complementares para explicar o contexto e o motivo do teste.
      placeholder: 
    validations:
      required: false
      
  - type: dropdown
    id: environment
    attributes:
      label: ">>Ambiente execucao<<"
      options:
        - DEV
        - HOM
