on:
  issues:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate file
        run: |
          > generated.txt
          git add .
          git commit -m "generated"
          git push