on:
  issues:
    types: [opened, reopened]

jobs:
  form-to-json:
    name: Convert Form Issue to JSON
    runs-on: ubuntu-latest
    steps:
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update yaml
        id: update-yaml
        uses: ./
        with:
          marks: ${{ fromJson(steps.parse.outputs.payload)['Marks'] }}
          ambiente: ${{ fromJson(steps.parse.outputs.payload)['Ambiente execucao'] }}

      - name: Atualizar repo
        run: |
          git config --global user.email "leosaglia@hotmail.com"
          git config --global user.name "Leo Saglia"
          git add .
          git commit -m "generated"
          git push               
    
  auto-closing-issue:
    name: Auto Closing Issue
    runs-on: ubuntu-latest
    needs: [form-to-json]
    steps:
      - name: Close Issue
        id: parse
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: Fechando issue automaticamente
