on:
  issues:
    types: [opened, reopened]

jobs:
  test-job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Script js
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            let teste = JSON.parse('{ "id_taac": "teste-id-taac" }').id_taac
            return teste
          result-encoding: string
      
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"

  #form-to-json:
  #  name: Convert Form Issue to JSON
  #  runs-on: ubuntu-latest
  #  outputs:
  #    ambiente_exec: ${{ steps.environ.outputs.ambiente_exec }}
  #  steps:
  #    - name: Run Issue form parser
  #      id: parse
  #      uses: peter-murray/issue-forms-body-parser@v2.0.0
  #      with:
  #        issue_id: ${{ github.event.issue.number }}
  #        separator: '###'
  #        label_marker_start: '>>'
  #        label_marker_end: '<<'

  #    - name: set environment output
  #      id: environ
  #      run: echo "ambiente_exec=${{ fromJson(steps.parse.outputs.payload)['Ambiente execucao'] }}" >> "$GITHUB_OUTPUT"

  #auto-closing-issue:
  #  name: Auto Closing Issue
  #  runs-on: ubuntu-latest
  #  needs: [form-to-json]
  #  steps:
  #    - name: test output
  #      env:
  #        ambiente_exec: ${{ needs.form-to-json.outputs.ambiente_exec }}
  #      run: echo $ambiente_exec

  #    - name: Close Issue
  #      id: parse
  #      uses: peter-evans/close-issue@v1
  #      with:
  #        issue-number: ${{ github.event.issue.number }}
  #        comment: Fechando issue automaticamente
