on:
  issues:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate file
        env:
          ACCESS_TOKEN:  ${{ secrets.SECRET_ACTIONS }}
        run: |
          > generated.txt
          echo ${{ github.event }}
          echo ${{ github.abrangencia }}
          git config --global user.email "leosaglia@hotmail.com"
          git config --global user.name "Leo Saglia"
          git add .
          git commit -m "generated"
          git push
